### ISSUE TITLE
I run the bot on linux and it doesn’t do anything

### ISSUE THREAD

**Issue by d86592** [ezelkow1/discord-key-bot#39]
I start the bot up, and i try a command and it doesn’t say anything or do anything. I check the command line and the bot stopped. I start it again but it still doesn’t work. No errors come up.

**Comment by ezelkow1** [comment]
If you get no output on the command line where you ran the bot then there is not much I can do. There are error logs for every startup error condition. If none of these print then Im just not sure. You can try running, file discord-key-bot, to get a print out of what type of executable your system thinks it is.

So unless there is actual output from where you tried to run it there isnt much I can do.  You can try building it yourself on that system if you have golang installed

If you run it on the command line with no options just, ./discord-key-bot, do you see any output? You should get a print out that there was no config file, at least then we know your system can actually run it

**Comment by d86592** [comment]
It says press control c to stop

**Comment by ezelkow1** [comment]
ok if it says that then the bot is running. There will be no other output since at that point you communicate to it through discord

**Comment by d86592** [comment]
I am not getting any response from the bot, even in the channel it is assigned to.

**Comment by ezelkow1** [comment]
What about sending messages in a DM to the bot, you should be able to do a !help in a DM and get a response

**Comment by d86592** [comment]
I do not get a response

**Comment by ezelkow1** [comment]
Do you actually see the bot online in discord, i.e. does it have the green circle and not an empty one? and do you have a proper bot token set in the config file? If the bot is online and setup properly then you should be able to message it through discord just fine

Also did you set a keyrole in the config file? If you have one set the bot will only communicate if you are a user with that same role, otherwise it wont respond

**Comment by d86592** [comment]
Oh thats why
