### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by reavscripts** [ezelkow1/discord-key-bot#41]
whenever i add a keyrole setting the bot give me this issue "panic: runtime error: index out of range"
if i leave keyrole blank the bot load without errors but not join or doing anything

i think i've setup everything as the README said is it outdated ? thanks for your work

**Comment by ezelkow1** [comment]
hmm Ill try to take a look at some point, I have been trying to find time to do a whole rewrite of it anyway to convert it to a sqlite db instead.

Does the role you are using exist and currently have members to it? I wonder if maybe the roles dont exist until theres a member and maybe its hitting some error with that (which would still be a bug in either case). Also just want to check you are using the actual name of the role, i.e. on my server we use `Keys` as the role and just have that in the config field

**Comment by reavscripts** [comment]
hi and thanks for the fast reply, yes the role i was using it was a test role i created and i putmyself in it, i used the ID for both role and channel
about using sql for me the best would be with less requirements possible
editing the key.json for me it would be really handy instead of having a sql database running for few uses

**Comment by ezelkow1** [comment]
For the config

For the broadcastchannel are you using the actual name of the channel? Or the ID number? The channel should be the discord number and not text, that you can find by running in dev mode in the client and right clicking on the channel.

The role should be the opposite, that should be the actual text name of the role

Just want to double check those are setup right since it can be a bit confusing the way you have to use them with the discord API

**Comment by reavscripts** [comment]
ehm, i told you already in the last message, yes im using the ID for both 

{
	"Token": "tokenblabla.X6PQAg.W_s_qpDLkKtJa3K4XBlaR3KXah0",
	"BroadcastChannel": "773848232111243265",
	"DbFile": "key.json",
	"KeyRole": "764956560665083905",
	"ListPMOnly": true
}

**Comment by ezelkow1** [comment]
ahh ok, so try using the actual text name for the role

**Comment by reavscripts** [comment]
![image](https://user-images.githubusercontent.com/72871071/98253882-e1859a80-1f7b-11eb-91f3-5d5788c9e848.png)

i hope this will make you understand better what my settings and what my errors

**Comment by ezelkow1** [comment]
thanks, yea Ill try to take a look at some point today if i can. Was just trying to get some initial info

**Comment by reavscripts** [comment]
thanks i will wait for an update keep up with good works

**Comment by ezelkow1** [comment]
Ahh ok I think I got it, its been so long since I actually had to make a new bot instance :). So the error comes from when discord sends the bot a message saying "ok the connection is all setup", however since the bot hasnt been invited to any servers yet all that information is blank.

So I think you still have to do the initial invite of your bot to your server. You can do that with this link:
https://discord.com/oauth2/authorize?client_id=123451234512345&scope=bot

replacing the number with the `client_id` that you can find under your discord developer portal for that bot in its general information area. That will let you officially invite that bot to whatever server you want. Then it should be able to properly join

**Comment by ezelkow1** [comment]
I should still see if theres a way to catch that error though and hand out the link since I still had to google around to find it

**Comment by ezelkow1** [comment]
I also just pushed a new linux release up that has a warning now if the bot detects this and will throw out that link
